---
vxlan:
  fabric:
    name: VXLAN_Site_3_Mgmt
    type: VXLAN_EVPN
  global:
    ibgp:
      bgp_asn: "65013"
      route_reflectors: 2
      anycast_gateway_mac: 12:34:56:78:90:00
      dns_servers:
        - ip_address: 10.0.0.2
          vrf: management
      ntp_servers:
        - ip_address: 10.55.0.2
          vrf: management
